name: flutter_ui_avatars
description: A Flutter implementation of https://ui-avatars.com/
version: 0.0.2
homepage: https://github.com/nmigueles/flutter_ui_avatars
repository: https://github.com/nmigueles/flutter_ui_avatars.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: